<div class="body">
	<div class="row remove-extra-space">
		<div class="col-md-8 remove-extra-space">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Libero volutpat sed cras ornare arcu dui vivamus. Facilisis mauris sit amet massa. Facilisis volutpat est velit egestas dui id ornare arcu odio. Vulputate sapien nec sagittis aliquam malesuada bibendum. Odio aenean sed adipiscing diam donec. Egestas fringilla phasellus faucibus scelerisque. Nec dui nunc mattis enim ut tellus. Amet massa vitae tortor condimentum lacinia quis. Nulla facilisi nullam vehicula ipsum a arcu cursus. At auctor urna nunc id cursus. Est placerat in egestas erat imperdiet sed. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Bibendum enim facilisis gravida neque convallis a cras semper. Sapien eget mi proin sed libero. In mollis nunc sed id semper. Ut consequat semper viverra nam libero justo laoreet sit. Adipiscing at in tellus integer feugiat scelerisque varius.

			Quis enim lobortis scelerisque fermentum dui. Ac orci phasellus egestas tellus rutrum. Morbi tincidunt augue interdum velit euismod in pellentesque massa. Accumsan tortor posuere ac ut consequat semper. Enim tortor at auctor urna nunc id cursus. Et leo duis ut diam. Eget sit amet tellus cras adipiscing enim eu. Venenatis cras sed felis eget velit aliquet sagittis. Enim sed faucibus turpis in eu mi. Amet justo donec enim diam vulputate. Dis parturient montes nascetur ridiculus mus mauris. In mollis nunc sed id semper risus in hendrerit. Nunc mattis enim ut tellus elementum sagittis. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Feugiat in fermentum posuere urna nec tincidunt praesent semper. Duis ut diam quam nulla porttitor massa. Eget duis at tellus at urna. Pulvinar neque laoreet suspendisse interdum consectetur. Ut diam quam nulla porttitor massa. Ultrices dui sapien eget mi proin sed libero enim.

			Egestas diam in arcu cursus euismod. Egestas integer eget aliquet nibh praesent tristique magna sit. Ipsum consequat nisl vel pretium lectus quam. Elementum tempus egestas sed sed risus pretium quam vulputate. Tincidunt augue interdum velit euismod. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Et netus et malesuada fames ac turpis. Enim neque volutpat ac tincidunt vitae semper quis lectus. Ut lectus arcu bibendum at varius vel pharetra. Nulla facilisi morbi tempus iaculis urna. Nec dui nunc mattis enim ut tellus elementum sagittis vitae. Sagittis eu volutpat odio facilisis mauris. Nunc faucibus a pellentesque sit amet. Id nibh tortor id aliquet lectus proin nibh nisl. Ornare massa eget egestas purus. Eu facilisis sed odio morbi quis commodo odio. Nulla pharetra diam sit amet. Et leo duis ut diam quam nulla porttitor massa id. Cras semper auctor neque vitae.

			Eros in cursus turpis massa tincidunt dui ut ornare lectus. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Sed felis eget velit aliquet sagittis id consectetur purus ut. Et netus et malesuada fames ac turpis egestas integer eget. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Accumsan lacus vel facilisis volutpat est velit egestas. Amet aliquam id diam maecenas. Morbi enim nunc faucibus a pellentesque sit. Elementum sagittis vitae et leo duis. Porta non pulvinar neque laoreet suspendisse interdum. Consectetur adipiscing elit pellentesque habitant morbi tristique. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Sagittis vitae et leo duis ut diam quam nulla. Consectetur adipiscing elit duis tristique. In hac habitasse platea dictumst quisque sagittis purus sit amet. Pellentesque elit eget gravida cum sociis natoque penatibus et. Nunc sed velit dignissim sodales. Lectus quam id leo in vitae.

			Mi ipsum faucibus vitae aliquet nec ullamcorper. Mauris rhoncus aenean vel elit scelerisque. Cursus eget nunc scelerisque viverra mauris in aliquam. At quis risus sed vulputate odio. Eu consequat ac felis donec et odio pellentesque diam. Non odio euismod lacinia at quis risus sed. Mattis aliquam faucibus purus in. Libero volutpat sed cras ornare arcu. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Pellentesque massa placerat duis ultricies lacus sed turpis. In mollis nunc sed id semper risus. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Nibh ipsum consequat nisl vel pretium lectus quam. Magna sit amet purus gravida quis blandit. Arcu dictum varius duis at consectetur lorem donec massa. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Eu volutpat odio facilisis mauris sit. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Ipsum a arcu cursus vitae congue. Lobortis mattis aliquam faucibus purus in massa.
		</div>
		<div class="col-md-4 remove-extra-space">

		</div>
	</div>
</div>
